//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProcCore.Business.DB0
{
    using System;
    using System.Collections.Generic;
    public partial class m_PurchaseDetail :BaseEntityTable {
    public int purchase_detail_id { get; set; }
    public string purchase_no { get; set; }
    public int item_no { get; set; }
    public string product_no { get; set; }
    public string product_name { get; set; }
    public int qty { get; set; }
    public int price { get; set; }
    public int sub_total { get; set; }
    public int kv { get; set; }
    public int kv_sub_total { get; set; }
    public string i_InsertUserID { get; set; }
    public Nullable<int> i_InsertDeptID { get; set; }
    public Nullable<System.DateTime> i_InsertDateTime { get; set; }
    public string i_UpdateUserID { get; set; }
    public Nullable<int> i_UpdateDeptID { get; set; }
    public Nullable<System.DateTime> i_UpdateDateTime { get; set; }
    public string i_Lang { get; set; }
    public Nullable<int> product_select_id { get; set; }
    public string style_name { get; set; }
    }
}
