//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProcCore.Business.DB0
{
    using System;
    using System.Collections.Generic;
    public partial class m_SettleCal :BaseEntityTable {
    public string sales_no { get; set; }
    public string sales_name { get; set; }
    public byte rank { get; set; }
    public string share_sn { get; set; }
    public string share_name { get; set; }
    public int share_level { get; set; }
    public int KV { get; set; }
    public string recommend_no { get; set; }
    public string recommend_name { get; set; }
    }
}
