//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProcCore.Business.DB0
{
    using System;
    using System.Collections.Generic;
    
    using Newtonsoft.Json;
    public partial class ProductCategory_l2 : BaseEntityTable
    {
        public ProductCategory_l2()
        {
            this.Product = new HashSet<Product>();
        }
    
        public int product_category_l2_id { get; set; }
        public int product_category_l1_id { get; set; }
        public string category_l2_name { get; set; }
        public int sort { get; set; }
        public bool i_Hide { get; set; }
    
    	[JsonIgnore]
        public virtual ProductCategory_l1 ProductCategory_l1 { get; set; }
    	[JsonIgnore]
        public virtual ICollection<Product> Product { get; set; }
    }
}
