//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProcCore.Business.DB0
{
    using System;
    using System.Collections.Generic;
    
    using Newtonsoft.Json;
    public partial class Purchase : BaseEntityTable
    {
        public Purchase()
        {
            this.PurchaseDetail = new HashSet<PurchaseDetail>();
            this.PaymentReply = new HashSet<PaymentReply>();
        }
    
        public string purchase_no { get; set; }
        public string sales_no { get; set; }
        public System.DateTime set_date { get; set; }
        public int total { get; set; }
        public Nullable<int> kv_total { get; set; }
        public int state { get; set; }
        public string i_InsertUserID { get; set; }
        public Nullable<int> i_InsertDeptID { get; set; }
        public Nullable<System.DateTime> i_InsertDateTime { get; set; }
        public string i_UpdateUserID { get; set; }
        public Nullable<int> i_UpdateDeptID { get; set; }
        public Nullable<System.DateTime> i_UpdateDateTime { get; set; }
        public string i_Lang { get; set; }
        public int source { get; set; }
        public int payby { get; set; }
        public int shipping_fee { get; set; }
        public string receive_person { get; set; }
        public string receive_tel { get; set; }
        public string receive_mobile { get; set; }
        public string receive_zip { get; set; }
        public string receive_address { get; set; }
        public string receive_city { get; set; }
        public string receive_country { get; set; }
        public string remit_number { get; set; }
        public Nullable<System.DateTime> remit_day { get; set; }
        public Nullable<System.TimeSpan> remit_time { get; set; }
        public Nullable<int> remit_money { get; set; }
        public string remit_memo { get; set; }
        public int pickup_state { get; set; }
        public string receive_memo { get; set; }
    
    	[JsonIgnore]
        public virtual Sales Sales { get; set; }
    	[JsonIgnore]
        public virtual ICollection<PurchaseDetail> PurchaseDetail { get; set; }
    	[JsonIgnore]
        public virtual ICollection<PaymentReply> PaymentReply { get; set; }
    }
}
