//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProcCore.Business.DB0
{
    using System;
    using System.Collections.Generic;
    
    using Newtonsoft.Json;
    public partial class Sales : BaseEntityTable
    {
        public Sales()
        {
            this.Purchase = new HashSet<Purchase>();
            this.SalesSub = new HashSet<Sales>();
            this.ShareSub = new HashSet<Sales>();
            this.SettleDetail = new HashSet<SettleDetail>();
        }
    
        public int sales_id { get; set; }
        public string sales_no { get; set; }
        public string sales_name { get; set; }
        public string account { get; set; }
        public string password { get; set; }
        public string address { get; set; }
        public bool gender { get; set; }
        public byte rank { get; set; }
        public string recommend_no { get; set; }
        public string recommend_name { get; set; }
        public byte share_sort { get; set; }
        public System.DateTime join_date { get; set; }
        public byte sales_state { get; set; }
        public Nullable<System.DateTime> birthday { get; set; }
        public string i_InsertUserID { get; set; }
        public Nullable<int> i_InsertDeptID { get; set; }
        public Nullable<System.DateTime> i_InsertDateTime { get; set; }
        public string i_UpdateUserID { get; set; }
        public Nullable<int> i_UpdateDeptID { get; set; }
        public Nullable<System.DateTime> i_UpdateDateTime { get; set; }
        public string i_Lang { get; set; }
        public string share_sn { get; set; }
        public int share_level { get; set; }
        public string zip { get; set; }
        public string tel { get; set; }
        public string mobile { get; set; }
        public string email { get; set; }
        public string city { get; set; }
        public string country { get; set; }
    
    	[JsonIgnore]
        public virtual ICollection<Purchase> Purchase { get; set; }
    	[JsonIgnore]
        public virtual ICollection<Sales> SalesSub { get; set; }
    	[JsonIgnore]
        public virtual Sales SalesParent { get; set; }
    	[JsonIgnore]
        public virtual ICollection<Sales> ShareSub { get; set; }
    	[JsonIgnore]
        public virtual Sales ShareParent { get; set; }
    	[JsonIgnore]
        public virtual ICollection<SettleDetail> SettleDetail { get; set; }
    }
}
