//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProcCore.Business.DB0
{
    using System;
    using System.Collections.Generic;
    
    using Newtonsoft.Json;
    public partial class SettleDetail : BaseEntityTable
    {
        public int settle_detail_id { get; set; }
        public int settle_id { get; set; }
        public string sales_no { get; set; }
        public string sales_name { get; set; }
        public byte rank { get; set; }
        public int y { get; set; }
        public int m { get; set; }
        public int kv_p_sum { get; set; }
        public int kv_g_sum { get; set; }
        public int kv_r_sum { get; set; }
        public int kv_l_sum { get; set; }
        public int kv_rc_sum { get; set; }
        public int a_p { get; set; }
        public int b_p { get; set; }
        public int a { get; set; }
        public int b { get; set; }
        public int bound { get; set; }
        public int center_bonus { get; set; }
        public int office_bonus { get; set; }
        public int count_manager { get; set; }
    
    	[JsonIgnore]
        public virtual Sales Sales { get; set; }
    	[JsonIgnore]
        public virtual Settle Settle { get; set; }
    }
}

